
export const REQ_PARTNERSHIPS_DATA= "REQ_PARTNERSHIPS_DATA"
export const GET_PARTNERSHIPS_DATA= "GET_PARTNERSHIPS_DATA"
export const FAIL_PARTNERSHIPS_DATA= "FAIL_PARTNERSHIPS_DATA"

export const REQ_TRIP_DATA= "REQ_TRIP_DATA"
export const GET_TRIP_DATA= "GET_TRIP_DATA"
export const FAIL_TRIP_DATA= "FAIL_TRIP_DATA"

export const REQ_INDIA_DATA= "REQ_INDIA_DATA"
export const GET_INDIA_DATA= "GET_INDIA_DATA"
export const FAIL_INDIA_DATA= "FAIL_INDIA_DATA"


export const REQ_HOTELS_DATA= "REQ_HOTELS_DATA"
export const GET_HOTELS_DATA= "GET_HOTELS_DATA"
export const FAIL_HOTELS_DATA= "FAIL_HOTELS_DATA"



export const REQ_BOOKHOTELS_DATA= "REQ_BOOKHOTELS_DATA"
export const GET_BOOKHOTELS_DATA= "GET_BOOKHOTELS_DATA"
export const FAIL_BOOKHOTELS_DATA= "FAIL_BOOKHOTELS_DATA"